---
title: "Untitled"
author: "Filippo Maganza"
date: "10/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Non-parametric methods

Non-parametric methods allow inference without making the assumption that the sample has been taken from a particular distribution.

Non-parametric are more robust, meaning that they can applied in a vastely range of samples.

## Permutation test

The permutation test, introduced by R. A. Fisher in the 1930s, is used to check the hypothesis that the two groups being compared have identical distributions. The idea of the test is to build the distribution of the test statistic under the null hypothesis by calculating all possible values of the test statistic under rearrangements of the group labels on the observed data points.

### Procedure of the test

Let $X_a = (X_{1a},...,X_{n_aa})$ and $X_2 = (X_{1b},...,X_{n_bb})$ be two samples drawn respectively from the population of group $a$ and from population of group $b$. Let $X_a = (X_{1a},...,X_{n_aa},X_{1b},...,X_{n_bb})$ be the pooled sample. Given the null hyphothesis $H_O: X_1=_dX_2$:

1. Compute the oberved test statistic $T(X) = S(X_a) − S (X_b)$ where $S$ is a symmetric (i.e. invariant with respect to the order of sample elements) and monotonic function such that large values of $T$ are evidence against $H_0$. A typical example of S is the sample mean.
2. Build the null reference distribution by computing the test statistic in 1 with all permutations of group label assignments.
3. Compute the p-value using $H_A$.

### Examples
<!-- Let $X_1$ be a random variable representing one population and $X_2$ the random variable representing another population. We can then formally define the following test: -->
<!-- $H_O: X_1=_dX_2 \;\;\;\; H_A: X_1>_dX_2$ -->
<!-- Here $=_d$ denotes $F_1(x)=F_2(x) \;\; \forall x \in  R_{X_1,X_2}$ and means "is equal in distribution to", and $>_d$ denotes $F_1(x)\leq F_2(x) \;\; \forall x \in  R_{X_1,X_2}$ (first-order stochastic dominance). -->




